### ISSUE TITLE
Apresentação Power Point

### ISSUE THREAD

**Issue by josinaldobarbosa** [josinaldobarbosa/LPVeiculos#1]
Com críticas ao projeto e a modelagem proposta, acompanhadas das soluções encontradas.
Todas as soluções devem estar implementadas no projeto entregue.

@carlos-renato , @wallacejsv

**Comment by carlos-renato** [comment]
Vou fazer minha crítica e disponibiliza-la para avaliação.

Carlos Renato
Graduação em Análise e Desenvolvimento de Sistemas
Classe 2014.3T- Manhã
INFNET

**Comment by carlos-renato** [comment]
Já disponibilizei uma proposta de mudança na modelagem... Está lá no Drive.

**Comment by josinaldobarbosa** [comment]
ok

**Comment by josinaldobarbosa** [comment]
Pronto.
