### ISSUE TITLE
1º - Missão

### ISSUE THREAD

**Issue by josinaldobarbosa** [josinaldobarbosa/LPVeiculos#4]
Bom vamos lá pessoal, tarefa bem simples.

@carlos-renato Ficou com a classe Carro.
@wallacejsv com a classe Motocicleta.

Fazer de acordo com a pre-modelagem do uml disponibilizado no GD, utilizando o padrão escolhido para o javadoc que também está lá, qualquer dúvida verifiquem a classe que está pronta. reclamações e choros entrem em contato.

OBS: quem for o primeiro a chegar criar o pacote: "br.com.lpveiculos.model.veiculos" onde pertence essas duas classes.

**Comment by jonathanvieiratt** [comment]
Show de bola!

Em 19 de abril de 2015 03:45, Josinaldo Albuquerque Barbosa <
notifications@github.com> escreveu:

**Comment by carlos-renato** [comment]
Mais que raio de pacote é esse???
huehuehue

Carlos Renato
Graduação em Análise e Desenvolvimento de Sistemas
Classe 2014.3T- Manhã
INFNET

**Comment by carlos-renato** [comment]
O que vocês acham de usarmos os cometários padrão para os getters e setters? Na hora de gerá-los via Eclipse, tem um opção para gerar esses comentários. Apliquei na classe "Carro". Deem uma olhada.

**Comment by carlos-renato** [comment]
Quero sugerir que "Carro" e "Moto" não herdem "tipo" (acho melhor "categoria") de "Veiculos", visto que carros e motos pertencem a categorias distintas.

**Comment by josinaldobarbosa** [comment]
Sobre o javadoc, o comentário "gerado" pelo que eu vi é exatamente só que em ingles, mas sem uma descrição só comentando os retornos e parâmetros, o que ficaria sem nada no "Method Summary" quando gerado o site...

**Comment by josinaldobarbosa** [comment]
Feito.
