### ISSUE TITLE
2º - Missão (Enumerações)

### ISSUE THREAD

**Issue by josinaldobarbosa** [josinaldobarbosa/LPVeiculos#5]
@wallacejsv Fazer as enumerações da classe Motocicleta.
@carlos-renato Fazer as enumerações da classe Carro.

Como decidido:
Classe Motocicleta e Carro: Montadora, Categoria, Cor, Cambio.

Colocar no pacote: model.veiculos.caracteristicas.NOMEDOVEICULO

**Comment by carlos-renato** [comment]
"Modelo" e "Tipo" são completamente diferentes para "Carro" e "Motocicleta". Por isso sugiro que "Carro" e "Motocicleta" tenham "Modelo" e "Tipo" distintos.

**Comment by josinaldobarbosa** [comment]
exatamente por isso está separado por pacote no "NOMEDOVEICULO"

**Comment by carlos-renato** [comment]
Será que "Modelo" é realmente uma enumeração??? Durante a vida da loja, diversos modelos surgirão (ex.: Corsa 2016/2017...).

**Comment by josinaldobarbosa** [comment]
Tb achei isso, mas não temos o método adicionar modelo...

**Comment by carlos-renato** [comment]
podemos colocar modelo nas classes Motocicleta e Carro. adicionar modelo é o mesmo que adicionar carro.

**Comment by jonathanvieiratt** [comment]
Galera, estou achando estranho ter que fazer enum para modelos..
Não seria muito grande?
é isso mesmo ?

2015-04-23 23:04 GMT-03:00 Carlos Renato notifications@github.com:

**Comment by carlos-renato** [comment]
Podes crer. Os modelos serão add na hora de cadastrar um carro/modelo. Na verdade modelo == carro.

**Comment by josinaldobarbosa** [comment]
o que diferencia um veiculo do outro será o seu chassi, modelo pode ser o mesmo para vários carros por exemplo.

**Comment by carlos-renato** [comment]
Já que o modelo pode ser o mesmo, porém há uma infinidade deles, essa não deve ser uma entrada do usuário?

**Comment by josinaldobarbosa** [comment]
Feito.
